displayName: Header transformer
type: middleware

import: github.com/adyanth/header-transform

summary: 'Transform headers including referring to other headers with full Regex support, see https://github.com/traefik/traefik/issues/6047'

testData:
  Rules:
    - Rule:
      Name: 'Header transformation'
      Header: 'X-Traefik-*'
      Value: 'X-custom'
      Type: 'Rename'
    - Rule:
      Name: 'Header addition'
      Header: 'NewHeader'
      Value: 'True'
      Type: 'Set'
    - Rule:
      Name: 'Header deletion'
      Header: 'Cache-Control'
      Type: 'Del'
    - Rule:
      Name: 'Header join'
      Header: 'Accept-Language'
      Sep: ', '
      Values:
        - 'Foo'
        - 'Bar'
      Type: 'Set'
